version: '3.8'

services:
    db:
      image: postgres:alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: anhthang123
        POSTGRES_DB: project

    back-end:
      build: .
      container_name: app_container
      ports:
        - "8080:8080"
      environment:
        - DB_URL=jdbc:postgresql://db:5432/project
        - DB_USERNAME=postgres
        - DB_PASSWORD=anhthang123
      depends_on:
        - db
      restart: always
